--- #YAML:1.0
build_requires:
  File::Find::Rule: 0.10
  Test::More: 0.47
conflicts: {}
distribution_type: module
license: perl
name: DateTime-Format-Mail
recommends:
  Test::Pod: 0.95
  Test::Signature: 1.04
requires:
  DateTime: 0.12
  Params::Validate: 0.59
version: 0.25
private:
  directory:
    - t
provides:
  DateTime::Format::Mail:
    file: lib/DateTime/Format/Mail.pm
    version: 0.25

generated_by: docmaker version 0.89
